### ISSUE TITLE
Team 2: Does the size of the bird effect the repair cost?

### ISSUE THREAD

**Issue by adrian-chen** [CSCI-4830-002-2014/hackathon-birdstrikes#10]
Does the size of the bird effect the repair cost?

**Comment by adrian-chen** [comment]
Possible Outcome: If there is a correlation, try not to hit big birds.

**Comment by indiesquidge** [comment]
It turns out that there is a correlation. If you look at the average cost for repair based on the size of the bird, larger birds _far_ out number that of medium and small birds, as seen below. A whopping average cost of $40,000 for larger birds vs. $4,000 for medium birds. Crazy difference.
![screen shot 2014-09-29 at 18 33 52](https://cloud.githubusercontent.com/assets/3409645/4451685/eb080c52-4839-11e4-8c97-1738d317130a.png)

However, if you look at number of times each incident actually occurs, small birds are far and wide more likely to be hit than large birds.
![screen shot 2014-09-29 at 18 38 48](https://cloud.githubusercontent.com/assets/3409645/4451702/2fb2a4e8-483a-11e4-95ff-9b0f70f1d4a5.png)

It would be difficult to just "try not to hit big birds". I don't think anyone is trying to hit the birds at all. But it is worth noting that the number of incidents involving larger birds is much less than smaller birds, but when it does happen, the cost is 10 fold.

**Comment by adrian-chen** [comment]
There isn't a lot we can do about this. Obviously, no pilots are trying to hit birds, flying at different elevations might change this, but there are reasons we fly at the elevations that we currently fly at. Not solvable.

**Comment by indiesquidge** [comment]
Well if you look at what altitude most birds are hit at (issue #33), a huge portion of it is when the plane is still on the ground. Depending on the bird sizes and species, I'm sure there are ways to decrease the number of birds. Perhaps there are bird sanctuaries nearby, or planes are flying in the opposite direction of migration patterns. This is definitely solvable, you just need to filter the data more to see where the main problem lies.
