### ISSUE TITLE
At what phase of the flight do the biggest birds come out to play?

### ISSUE THREAD

**Issue by justinmcbride** [CSCI-4830-002-2014/hackathon-birdstrikes#29]
During the different phases of flight, what is the distribution of sizes of the animals that got hit?
# Option 1:

Bigger birds are heavier, and do not fly as high. Higher speeds should be allowed because the impact would be less severe. 
# Option 2:

Any size animal is a hazard during a take off, and special care should be taken to avoid them.

**Comment by LoganBates** [comment]
![image](https://cloud.githubusercontent.com/assets/3269358/4451603/5a97fffc-4838-11e4-859c-68ac7ae4ea40.png)

Birds tend to get hit more when the plane is near the airport (climb, approach, takeoff, landing). Big birds are actually hit the least frequently by the measured trends. Small birds have a death wish, but it's probably because they tend to flock together. It seems that different bird sizes don't tend to chill at different flight phases though.
