### ISSUE TITLE
Team 1: When is a bird more commonly hit night or day?

### ISSUE THREAD

**Issue by jakecharland** [CSCI-4830-002-2014/hackathon-birdstrikes#3]
When is a bird more commonly hit, during the day or at night?

**Comment by justinmcbride** [comment]
![tabch3](https://cloud.githubusercontent.com/assets/7710325/4451777/4c6b7d70-483b-11e4-85fe-9a7ea1b95398.png)

More birds are hit during the day, but it's probably due to more flights being made through the day, rather than at night. Additionally, the average number of human fatalities is higher during the day than during the night, leading one to believe flying at night is safer.
