### ISSUE TITLE
At what average altitude do the different sizes of birds fly? Does this altitude correlate with the size of bird hit? [Team 1]

### ISSUE THREAD

**Issue by LoganBates** [CSCI-4830-002-2014/hackathon-birdstrikes#30]
Where do different sized birds like to hang out? Is there a stronger correlation between bird altitude or bird size and instances of birds being hit? 

Possible outcomes:
Fat birds don't fly as high but they're bigger and easier to hit. Big birds will most likely fly lower and create more impacts.

**Comment by dano8957** [comment]
![Photo](http://imgur.com/43L2blG.png)

**Comment by dano8957** [comment]
![Bird Altitude vs. Bird Size](http://imgur.com/i4HFGO3.png)

**Comment by dano8957** [comment]
On average, small and medium birds tend to get hit more in every phase of the flight in higher altitudes. This may be due to the fact that medium and small birds stay in large flocks and have a higher likelihood of being struck by a plane. Large and unidentified birds tend to get hit at lower altitudes, maybe to to them not flying as fast or being too slow to not avoid death. But large birds on average fly at higher altitudes than where they get struck by planes. This shows that the altitude of a bird doesn't completely correlate with the altitude the sized bird is struck at.

**Comment by dano8957** [comment]
![Photo](http://imgur.com/pQGmqrs.png)

**Comment by dano8957** [comment]
Most bird strikes happen during the descent and en route to the airport.
